# Generated by Django 4.1.2 on 2022-10-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('informacion', models.TextField()),
                ('sugerido_para', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
