# Generated by Django 4.1.2 on 2022-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='informacion',
            field=models.CharField(max_length=500),
        ),
    ]
