# Generated by Django 4.1.2 on 2022-10-21 21:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_destino_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_destino',
            field=models.ImageField(blank=True, null=True, upload_to='destinos'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='informacion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
