# Generated by Django 4.1.2 on 2022-10-30 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destino_fecha_modificacion_destino_foto_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2022, 10, 30)),
        ),
    ]
